name: code_base
description: base Flutter
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^2.1.2
  dartz: ^0.10.1
  get_it: ^7.6.0
  get: ^4.6.5
  dio: 5.4.1
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  json_annotation: 4.8.1
  analyzer: 6.2.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.1.0
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
